### ISSUE TITLE
Current limit: 28 instead of 30

### ISSUE THREAD

**Issue by mrrivest** [lijon/BafangWebConfig#8]
On a BBSHD, I would like to set the current limit to 30. However the config tool has a limit of 28, before throwing a "current limit out of range" error.

**Comment by lijon** [comment]
The tool has a max value of 30 (it's set in the text field in the html file). The error you're receiving is from the BBSHD controller so it's not because of any limit applied by this tool.
A quick google search suggests that some (52V) BBSHDs are limited to 28A, while others (48V) is limited to 30A (which makes sense if considering the effect (Watts = Volts x Amps) instead of amps only).
